#!/usr/bin/env python

import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib2
import urlparse


BASE_PATH = '/tmp/AA'


def execute_install(app, script):
    name = app['name']
    version = app['version']
    # download tar
    url = urlparse.urljoin(app['base_url'],
                           app.get('tar_file',
                                   '%s-%s.tar.gz' % (name, version)))
    tar = tempfile.NamedTemporaryFile(delete=False)
    req = urllib2.urlopen(url)
    with tar:
        shutil.copyfileobj(req, tar)
    app_dir = os.path.join(BASE_PATH, '%s-%s' % (name, version))
    shutil.rmtree(app_dir, ignore_errors=True)
    # execute installer
    command = [script,
                name,
                version,
                tar.name,
                app_dir,
                os.path.join(BASE_PATH, 'src')]
    sys.exit(subprocess.call(command))


if __name__ == '__main__':
    config = json.loads(sys.stdin.read())
    print "*" * 40
    print config
    print "*" * 40
    execute_install(config, sys.argv[1])
