#!/usr/bin/env python

import json
import os
import shutil
import subprocess
import sys
import tempfile
import urllib2
import urlparse


BASE_PATH = '/tmp/AA'


def execute_install(app, script):
    name = app['name']
    version = app['version']
    # download tar
    base_url = app['config']['base_url']
    tar_file = app['config'].get('tar_file',
                                 '%s-%s.tar.gz' % (name, version))
    url = urlparse.urljoin(base_url, tar_file)
    tar = tempfile.NamedTemporaryFile(delete=False)
    req = urllib2.urlopen(url)
    with tar:
        shutil.copyfileobj(req, tar)
    app_dir = os.path.join(BASE_PATH, '%s-%s' % (name, version))
    shutil.rmtree(app_dir, ignore_errors=True)
    # execute installer
    command = [script,
                name,
                version,
                tar.name,
                app_dir,
                os.path.join(BASE_PATH, 'src')]
    sys.exit(subprocess.call(command))


if __name__ == '__main__':
    app_info = json.loads(sys.stdin.read())
    execute_install(app_info, sys.argv[1])
